### ISSUE TITLE
"Auth requestes in embedded browsers will be blocked"

### ISSUE THREAD

**Issue by chmiiller** [ejci/Google-Auth-for-Titanium#13]
A while ago I've started to receive this message:
![gauth](https://cloud.githubusercontent.com/assets/1013632/23070234/b059d27a-f52a-11e6-9ba0-b427b4c7b4dd.png)
on my app.
What are you using for Gmail login/account creation on your apps? Won't be possible to keep using this option after April!

Thanks!

**Comment by chmiiller** [comment]
The "learn more" button redirects to: https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

**Comment by varun0294** [comment]
Did you find any solution?

**Comment by ChanakyaSrinivas** [comment]
Hi ,

is there any solution?

**Comment by chmiiller** [comment]
Yes! We now have two different native modules for this:
[This one for iOS](https://github.com/hansemannn/titanium-google-signin) and [this one for Android!](https://github.com/AppWerft/Ti.GoogleSignIn)
Create issues on the module repo if you have questions on how to use it!
Bests!

**Comment by ChanakyaSrinivas** [comment]
As per your suggestion, I tried with above module. but I was unable get the Google authentication Access Token.
How to get the Google authentication Access Token ?
