### ISSUE TITLE
the redirect uri in the request  urn:ietf:wg:oauth:2.0:oob did not match a register redirect url

### ISSUE THREAD

**Issue by abada** [ejci/Google-Auth-for-Titanium#4]
the redirect uri in the request  urn:ietf:wg:oauth:2.0:oob did not match a register redirect url

sdk :3.4.1 GA
android 4.4.4

**Comment by ejci** [comment]
Can you pls elaborate? If possible pls also add log.
Is you API key correctly configured?

**Comment by abada** [comment]
Please see this photo
![img_0545](https://cloud.githubusercontent.com/assets/180586/5606557/c9e5ec5c-943c-11e4-830a-2e5ba7c70cdd.jpg)

**Comment by ejci** [comment]
This looks like a misconfiguration on API console.
How did you configured the API?

**Comment by abada** [comment]
Thanks for help
![screen shot 2015-01-04 at 8 47 54 pm](https://cloud.githubusercontent.com/assets/180586/5607079/4db61892-9454-11e4-8cd9-de52c6d140e5.png)

**Comment by ejci** [comment]
You need to create a new Client ID with different "Application type." You need to pick "Installed application":
![screen shot 2015-01-04 at 19 59 37](https://cloud.githubusercontent.com/assets/1025656/5607095/58bcf560-944c-11e4-936b-a536a90618d8.png)

**Comment by abada** [comment]
@ejci  Thanks it`s working

**Comment by brunonavarro** [comment]
I have the same problem but the provider is Asana auth, please could you share how you added that URL in the manifest?
