### ISSUE TITLE
Integration of Google Plus with Titanium

### ISSUE THREAD

**Issue by SPorwal** [ejci/Google-Auth-for-Titanium#5]
Hi Miroslav,

I am trying to integrate my app login with Google+. Can you please help me to do this?

Thanks,
Shraddha

**Comment by ejci** [comment]
Can you pls elaborate. Whats the problem? Where are you stuck?

**Comment by SPorwal** [comment]
I added the module and enabled Google+ api in console. On running the application, it asks for Google account authorization. What changes in 'googleAuth.js' should be made to use Google+ instead of Google account? I guess the oAuth process is same for both.

**Comment by ejci** [comment]
Yes the library can be used with all google oAuthAPIs. You just need to have correct settings in Google API console and use right "scope".
Whats is error log saying? Do you have any errors there?

**Comment by SPorwal** [comment]
I used these scopes in scope parameter: ['https://www.googleapis.com/auth/plus.login', 'profile', 'email', 'openid']

and got this response

{
  "code": 0,
  "source": {
    "location": "https://www.googleapis.com/auth/plus.me?access_token=yxxx.NAFtxQq2lgIN8pJ4m-w1BztpI9ft6i2wQaNSO_OtsUIsFSGSoJoZoYLq1pBw",
    "status": 200,
    "autoEncodeUrl": true,
    "timeout": 10000,
    "domain": null,
    "responseText": "plus.me",
    "autoRedirect": true,
    "connectionType": "GET",
    "validatesSecureCertificate": false,
    "statusText": "OK",
    "password": null,
    "allResponseHeaders": "Content-Type:text/plain\nDate:Thu, 12 Mar 2015 10:06:54 GMT\nExpires:Thu, 12 Mar 2015 10:06:54 GMT\nCache-Control:private, max-age=0\nX-Content-Type-Options:nosniff\nX-Frame-Options:SAMEORIGIN\nX-XSS-Protection:1; mode=block\nServer:GSE\nAlternate-Protocol:443:quic,p=0.08\nAccept-Ranges:none\nVary:Accept-Encoding\nTransfer-Encoding:chunked\n",
    "readyState": 4,
    "responseXML": null,
    "responseData": {
      "file": null,
      "nativePath": null,
      "height": 0,
      "length": 7,
      "width": 0,
      "mimeType": "text/plain",
      "apiName": "Ti.Blob",
      "text": "plus.me",
      "type": 2,
      "bubbleParent": true
    },
    "apiName": "Ti.Network.HTTPClient",
    "username": null,
    "connected": false,
    "bubbleParent": true,
    "_events": {
      "disposehandle": {
        
      }
    }
  },
  "success": true
}

I was expecting to get user info in the response but didn't get. Can you tell me where is the mistake?

**Comment by ejci** [comment]
Hard to tell whats wrong.... So the library is working (you received the token) but you didnt get the data from API...

I would suggest to try your calls here:
https://developers.google.com/oauthplayground/
You can test all responses there

But my first idea will be to change the scopes to this: ['https://www.googleapis.com/auth/plus.login','https://www.googleapis.com/auth/plus.login','https://www.googleapis.com/auth/plus.me']

**Comment by SPorwal** [comment]
Thanks. I tried the call with oaothplayground.

The query was wrong. I changed the query and got the response there. But in my app, I am not getting the response and getting some unknown error - not able to parse that too.

    client.open("GET", "https://www.googleapis.com/auth/plus/v1/people/me");
    client.setRequestHeader("Authorization","Bearer "+accessToken);
    client.setRequestHeader("Content-Type", "application/json");
    client.send();

This is the part of code. Can you tell me if anything is wrong here? Or am I missing something?(I tried with appending access token in the end of the url but no luck.)

**Comment by ejci** [comment]
Can you paste the response?

**Comment by SPorwal** [comment]
[ERROR] :  TiHttpClient: (TiHttpClient-1) [29054,29054] HTTP Error (org.apache.http.client.HttpResponseException): Not Found
    [ERROR] :  TiHttpClient: org.apache.http.client.HttpResponseException: Not Found
    [ERROR] :  TiHttpClient: 	at ti.modules.titanium.network.TiHTTPClient$LocalResponseHandler.handleResponse(TiHTTPClient.java:275)
    [ERROR] :  TiHttpClient: 	at ti.modules.titanium.network.TiHTTPClient$LocalResponseHandler.handleResponse(TiHTTPClient.java:219)
    [ERROR] :  TiHttpClient: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:677)
    [ERROR] :  TiHttpClient: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:657)
    [ERROR] :  TiHttpClient: 	at ti.modules.titanium.network.TiHTTPClient$ClientRunnable.run(TiHTTPClient.java:1334)
    [ERROR] :  TiHttpClient: 	at java.lang.Thread.run(Thread.java:841)


Nothing more than this.

**Comment by ejci** [comment]
This looks like something with Titanium to me...
Its really strange error.

**Comment by SPorwal** [comment]
Thanks @ejci for the help.
