### ISSUE TITLE
Use titaniumifier

### ISSUE THREAD

**Issue by yuchi** [ejci/Google-Auth-for-Titanium#7]
If you use [titaniumifier](https://github.com/smclab/titaniumifier) you would have npm support and, more importantly, `gitTio` exposure.

Have a look at the [Wiki](https://github.com/smclab/titaniumifier/wiki) for documentation and to the [Getting Started page](https://github.com/smclab/titaniumifier/wiki/Getting-Started) to get up and running.

Let me know if you need any info if you’re interested.

**Comment by ejci** [comment]
Good idea. I will look into it

**Comment by yuchi** [comment]
Closing for obsolescence.

I still suggest to move to titaniumifier, if you still keep maintaining this project.
